create table if not exists public.telegram_bot_events (
  id bigint generated by default as identity primary key,
  user_hash text not null,
  event_type text not null check (char_length(event_type) between 2 and 50),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists telegram_bot_events_user_idx
  on public.telegram_bot_events (user_hash);
create index if not exists telegram_bot_events_type_date_idx
  on public.telegram_bot_events (event_type, created_at desc);

alter table public.telegram_bot_events enable row level security;
revoke all on public.telegram_bot_events from anon, authenticated;
revoke all on sequence public.telegram_bot_events_id_seq from anon, authenticated;

create or replace function public.get_telegram_bot_stats()
returns jsonb
language sql
security definer
set search_path = ''
as $$
  with event_counts as (
    select
      count(distinct user_hash) as total_unique_users,
      count(*) filter (where event_type = 'start') as total_starts,
      count(*) filter (where event_type = 'movie_request') as total_movie_requests,
      count(*) filter (where event_type = 'delivery') as total_deliveries,
      count(*) filter (where event_type = 'report') as total_reports,
      count(distinct user_hash) filter (
        where created_at >= date_trunc('day', now() at time zone 'Asia/Kolkata')
          at time zone 'Asia/Kolkata'
      ) as today_unique_users,
      count(*) filter (
        where event_type = 'delivery'
          and created_at >= date_trunc('day', now() at time zone 'Asia/Kolkata')
            at time zone 'Asia/Kolkata'
      ) as today_deliveries
    from public.telegram_bot_events
  )
  select jsonb_build_object(
    'total_unique_users', total_unique_users,
    'total_starts', total_starts,
    'total_movie_requests', total_movie_requests,
    'total_deliveries', total_deliveries,
    'total_reports', total_reports,
    'today_unique_users', today_unique_users,
    'today_deliveries', today_deliveries
  )
  from event_counts;
$$;

revoke all on function public.get_telegram_bot_stats() from public, anon, authenticated;
grant execute on function public.get_telegram_bot_stats() to service_role;
